// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: School.proto

package app;

public interface SchoolOrBuilder extends
    // @@protoc_insertion_point(interface_extends:School)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string EmployeeId = 2;</code>
   */
  java.lang.String getEmployeeId();
  /**
   * <code>string EmployeeId = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeIdBytes();

  /**
   * <code>string Designation = 3;</code>
   */
  java.lang.String getDesignation();
  /**
   * <code>string Designation = 3;</code>
   */
  com.google.protobuf.ByteString
      getDesignationBytes();

  /**
   * <code>string Company = 4;</code>
   */
  java.lang.String getCompany();
  /**
   * <code>string Company = 4;</code>
   */
  com.google.protobuf.ByteString
      getCompanyBytes();
}
